services:
  app:
    container_name: app-dev
    build:
      args:
        - PYTHON_BASE_IMAGE=mcr.microsoft.com/vscode/devcontainers/python
    command: sleep infinity
    volumes:
      - .:/workspace:cached
